
IF NOT EXISTS(SELECT * from sys.indexes I INNER JOIN
sys.objects T ON I.object_id=T.object_id
WHERE I.name = 'IDX_DINAMIKUP_STOK_HAREKETLERI' AND T.name='STOK_HAREKETLERI' AND T.type='U') 
CREATE NONCLUSTERED INDEX IDX_DINAMIKUP_STOK_HAREKETLERI ON [dbo].[STOK_HAREKETLERI]
(
	[sth_tip] ASC,
	[sth_cins] ASC,
	[sth_normal_iade] ASC,
	[sth_stok_kod] ASC,
	[sth_tarih] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];

GO
